# ===============================
# Application
# ===============================
spring.application.name=backend

# ===============================
# Database - PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://db:5432/IAcademy
spring.datasource.username=appuser
spring.datasource.password=secret

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Server
# ===============================
server.address=0.0.0.0
server.port=8080

# ===============================
# Stripe
# ===============================
stripe.secretKey=sk_test_51T7bGHCvFcs5PVyN8ai7CZlzLmB7OfwyPfNNU74WwnrjEgRmDTKHOapQ48M8jbic8rtohhY6sk0QDRFXT1OHe57P00p3G8oPbs
stripe.webhookSecret=
app.frontendSuccessUrl=
app.frontendCancelUrl=frontend://payment-cancel